import { Modal, BlockStack, CalloutCard } from "@shopify/polaris";
import React from "react";
import { DiffCard } from "../../DiffCard";

interface FixReviewModalProps {
  open: boolean;
  onClose: () => void;
  selectedFix: any;
  isLoading: boolean;
  onConfirm: () => void;
  onUndo: (id: string) => void;
}

export const FixReviewModal = ({
  open,
  onClose,
  selectedFix,
  isLoading,
  onConfirm,
  onUndo,
}: FixReviewModalProps) => {
  if (!selectedFix) return null;

  const productTitle =
    selectedFix.productTitle ||
    (selectedFix.productId ? "Product" : "Global Issue");

  return (
    <Modal
      open={open}
      onClose={onClose}
      title={`Review Optimization for ${productTitle}`}
      primaryAction={
        selectedFix.status === "RESOLVED"
          ? {
              content: "Revert Change",
              onAction: () => onUndo(selectedFix.id),
              destructive: true,
              loading: isLoading,
            }
          : {
              content: "Apply Fix",
              onAction: onConfirm,
              loading: isLoading,
              disabled: !selectedFix.suggestedValue,
            }
      }
      secondaryActions={[
        {
          content: "Cancel",
          onAction: onClose,
          disabled: isLoading,
        },
      ]}
      size="large"
    >
      <Modal.Section>
        <BlockStack gap="400">
          <DiffCard
            fix={selectedFix}
            onApply={() => onConfirm()} // DiffCard internal button calls this
            onUndo={() => onUndo(selectedFix.id)}
            isApplying={isLoading}
            isUndoing={isLoading}
            // shop="myshopify.com" // Mock shop if needed, or pass prop
          />
          {selectedFix.status !== "RESOLVED" && (
            <CalloutCard
              title="AI-Generated Suggestion"
              illustration="https://cdn.shopify.com/s/files/1/0262/4071/2726/files/emptystate-files.png"
              primaryAction={{
                content: "Apply Changes",
                onAction: onConfirm,
                loading: isLoading,
              }}
            >
              <p>
                This suggestion was generated by AI based on your product
                details and SEO best practices. Review the changes above before
                applying them to your live store.
              </p>
            </CalloutCard>
          )}
        </BlockStack>
      </Modal.Section>
    </Modal>
  );
};
